/*INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Inspection Finances', 'Inspection Générale des Finances', '', 'IGF');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Douane', 'Administration des Douanes & Impôts Indirects', '', 'ADII');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Trésorie', 'Trésorerie Générale du Royaume', '', 'TGR');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Impots', 'Direction Générale des Impôts', '', 'DGI');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Budget', 'Direction du Budget', '', 'DDB');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Tresor et finances Extérieure', 'Direction du Trésor et des Finances Extérieures', '', 'DTFE');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Previsions financieres', 'Direction des Etudes & des Prévisions Financières', '', 'DEPF');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Judiciaire', 'Agence Judiciaire du Royaume', '', 'AJR');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Entreprises et privatisation', 'Direction des Entreprises Publiques et de la Privatisation', '', 'DEPP');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Affaires Administration et Générale', 'Direction des Affaires Administratives & Générales', '', 'DAAG');
INSERT INTO directions (direction_id, description, fonction, intitled, logo, nom)
VALUES (NULL,'' , 'Domaines de l''''Etat', 'Direction des Domaines de l''Etat', '', 'DDE');




INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Harrouda');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Yakhlef');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouskoura');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Casablanca');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Médiouna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Mohammadia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tit Mellil');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Yakhlef');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bejaâd');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Ahmed');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0, 'Benslimane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Berrechid');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boujniba');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boulanouare');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouznika');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Deroua');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Borouj');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Gara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Guisser');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Hattane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khouribga');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Loulad');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Zem');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Abbou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad H''Riz Sahel');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad M''rah');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Saïd');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Sidi Ben Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ras El Aïn');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Settat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Rahhal Chataï');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Soualem');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Azemmour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bir Jdid');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouguedra');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Echemmaia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Jadida');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Hrara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ighoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jamâat Shaim');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jorf Lasfar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khemis Zemamra');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Laaounate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Abdallah');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oualidia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Amrane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Frej');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Ghadbane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Safi');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sebt El Maârif');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sebt Gzoula');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Ahmed');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Ali Ban Hamdouche');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Bennour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Bouzid');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Smaïl');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Youssoufia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Fès');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Cheggag');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bhalil');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boulemane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Menzel');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Guigou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Imouzzer Kandar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Imouzzer Marmoucha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Missour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Yaâcoub');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ouled Tayeb');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Outat El Haj');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ribate El Kheir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Séfrou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Skhinate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tafajight');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Arbaoua');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Dorij');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dar Gueddari');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Had Kourt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jorf El Melha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kénitra');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khenichet');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lalla Mimouna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Mechra Bel Ksiri');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Mehdia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Bousselham');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Allal Tazi');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Kacem');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Slimane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Taibi');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Yahya El Gharb');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Souk El Arbaa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Akka');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Assa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouizakarne');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Ouatia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Es-Semara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Fam El Hisn');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Foum Zguid');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Guelmim');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taghjijt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tan-Tan');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tata');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zag');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Marrakech');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');

INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ait Daoud');

INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Amizmiz');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Assahrij');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Ourir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Guerir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Chichaoua');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Hanchane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Kelaâ des Sraghna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Essaouira');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Fraïta');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ghmate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ighounane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Imintanoute');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kattara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lalla Takerkoust');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Loudaya');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lâattaouia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Brahim');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Mzouda');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ounagha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sid L''Mokhtar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sid Zouin');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Abdallah Ghiat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Bou Othmane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Rahhal');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Skhour Rehamna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Smimou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tafetachte');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tahannaout');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Talmest');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamallalt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamanar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamansourt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tameslouht');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tanalt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zeubelemok');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Meknès‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khénifra');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Agourai');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ain Taoujdate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'MyAliCherif');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Rissani');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Amalou Ighriben');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aoufous');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Arfoud');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Azrou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Jemaa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Karma');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Leuh');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Boubidmane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Ishaq');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boudnib');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boufakrane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boumia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Hajeb');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Elkbab');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Er-Rich');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Errachidia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Gardmit');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Goulmima');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Gourrama');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Had Bouhssoussen');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Haj Kaddour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ifrane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Itzer');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jorf');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kehf Nsour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kerrouchen');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'M''haya');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'M''rirt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Midelt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Ali Cherif');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Bouazza');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moulay Idriss Zerhoun');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moussaoua');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'N''Zalat Bni Amar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ouaoumana');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Ifrane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sabaa Aiyoun');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sebt Jahjouh');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Addi');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tichoute');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tighassaline');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tighza');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Timahdite');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tinejdad');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tizguite');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Toulal');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tounfite');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zaouia d''Ifrane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zaïda');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ahfir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aklim');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Al Aroui');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Bni Mathar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aïn Erreggada');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Taïeb');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Berkane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Ansar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Chiker');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Drar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Tadjite');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouanane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouarfa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bouhdila');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dar El Kebdani');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Debdou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Douar Kannine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Driouch');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Aïoun Sidi Mellouk');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Farkhana');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Figuig');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ihddaden');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jaâdar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jerada');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kariat Arekmane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kassita');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kerouna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Laâtamna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Madagh');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Midar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Nador');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Naima');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Heimer');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oujda');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ras El Ma');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Saïdia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Selouane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Boubker');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Slimane Echcharaa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Talsint');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taourirt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tendrara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tiztoutine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Touima');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Touissit');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zaïo');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zeghanghane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Rabat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Salé');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ain El Aouda');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Harhoura');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khémisset');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulmès');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Rommani');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Allal El Bahraoui');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Bouknadel');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Skhirate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamesna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Témara');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tiddas');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tiflet');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Touarga');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Agadir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Agdz');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Agni Izimmer');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Melloul');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Alnif');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Anzi');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aoulouz');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aourir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Arazane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Baha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Iaâza');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Yalla');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ben Sergao');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Biougra');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boumalne-Dadès');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dcheira El Jihadia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Drargua');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Guerdane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Harte Lyamine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ida Ougnidif');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ifri');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Igdamen');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ighil n''Oumgoun');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Imassine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Inezgane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Irherm');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kelaat-M''Gouna');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lakhsas');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lakhsass');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Lqliâa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'M''semrir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Massa (Maroc)');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Megousse');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ouarzazate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Berhil');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Teïma');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sarghine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Ifni');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Skoura');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tabounte');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tafraout');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taghzout');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tagzen');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taliouine');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamegroute');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamraght');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tanoumrite Nkob Zagora');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taourirt ait zaghar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taroudannt');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Temsia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tifnit');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tisgdal');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tiznit');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Toundoute');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zagora');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Afourar');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aghbala');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Azilal');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Majden');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Beni Ayat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Béni Mellal');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bin elouidane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bradia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bzou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dar Oulad Zidouh');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Demnate');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dra''a');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Ksiba');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Foum Jamaa');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Fquih Ben Salah');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Kasba Tadla');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ouaouizeght');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Ayad');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad M''Barek');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Yaich');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Jaber');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Souk Sebt Oulad Nemma');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zaouïat Cheikh');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tanger‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tétouan‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Akchour');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Assilah');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bab Berred');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bab Taza');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Brikcha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Chefchaouen');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dar Bni Karrich');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Dar Chaoui');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Fnideq');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Gueznaia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Jebha');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Karia');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Khémis Sahel');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ksar El Kébir');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Larache');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'M''diq');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Martil');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Moqrisset');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Laou');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Rmel');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ouazzane');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Point Cires');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Lyamani');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Sidi Mohamed ben Abdallah el-Raisuni');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Zinat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ajdir‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aknoul‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Al Hoceïma‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Hichem‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Bouayach‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Bni Hadifa‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Ghafsai‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Guercif‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Imzouren‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Inahnahen‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Issaguen (Ketama)‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Karia (El Jadida)‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Karia Ba Mohamed‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued Amlil‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oulad Zbair‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tahla‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tala Tazegwaght‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tamassint‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taounate‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Targuist‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taza‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Taïnaste‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Thar Es-Souk‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tissa‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tizi Ouasli‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Laayoune‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'El Marsa‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Tarfaya‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Boujdour‎');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Awsard');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Oued-Eddahab');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Stehat');
INSERT INTO ville (latitude_ville,longitude_ville,nom_ville) VALUES(0,0,'Aït Attab');


INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Administrateurs de 1er grade');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Administrateurs de 2ème grade');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Techniciens ');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Ingénieurs d’Etat, Architectes et
Ingénieurs de 1er grade');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Ingénieurs d’Etat, Architectes et
Ingénieurs de 2ème grade');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Inspecteurs des Finances ');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Rédacteurs ');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Adjoints Techniques  ');
INSERT INTO grades(id_grade,intitled_grade) VALUES(NULL,'Adjoints Administratifs  ');
*/
